make it work with repoman/vmstore. cleaned-up and robustified bash routines.

diff --git a/scripts/condor/worker/cloud_scheduler b/scripts/condor/worker/cloud_scheduler
--- a/scripts/condor/worker/cloud_scheduler
+++ b/scripts/condor/worker/cloud_scheduler
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/bin/bash
 #
 # Init script for cloud scheduler client to modify 
 # local condor configurations
@@ -6,139 +6,108 @@
 # chkconfig: 2345 90 10
 # description: Cloud Scheduler modify condor script
 #
-# config: /etc/cloud_scheduler/condor.conf
-
 # Source function library
 . /etc/rc.d/init.d/functions
 
-# Path to your primary condor configuration file
-CONDOR_CONFIG=/etc/condor/condor_config
+# Source cloud scheduler special configurations
+. /etc/sysconfig/cloud_scheduler
 
-# Path to condor_config_val
-CONDOR_CONFIG_VAL="/usr/bin/condor_config_val"
+IFCONFIG=/sbin/ifconfig
+PYTHON=python26
+CONDOR_CONFIG_VAL=/usr/bin/condor_config_val
 
 # Emits error with a "FATAL: " prefix. Exits.  Never returns
 fatal_error() {
-    echo "FATAL: $1"
+    echo "FATAL: $1" 1>&2
     exit 1
 }
 
 # Returns a setting from the CONDOR_CONFIG configuration
-# file.  Exits if the value cannot be found!
+# file. Exits if the value cannot be found!
 get_condor_config_val() {
-    TMPVAL=`"$CONDOR_CONFIG_VAL" $1`
-    if [ "$TMPVAL" = "" ]; then
-	fatal_error "Unable to locate $1 in $CONDOR_CONFIG"
-    fi
-    echo "$TMPVAL"
+    local val="$(${CONDOR_CONFIG_VAL} $1)"
+    [[ -z ${val} ]] && fatal_error "Variable $1 is not defined with condor"
+    echo "${val}"
 }
 
-replace_or_append() {
-    replace_this=$1
-    with_this=$2
-    on_this_file=$3
-
-    grep -e "^$replace_this[ =]" $on_this_file >/dev/null 2>&1
-    REPLACE=$?
-    if [ $REPLACE -eq 0 ]; then
-	sed -i "s/^$replace_this[ =].*/$with_this/" $on_this_file
+# Update the condor config file with KEY=VAL
+update_condor_config() {
+    : ${CONDOR_CONFIG_LOCAL:=$(get_condor_config_val LOCAL_CONFIG_FILE)}
+    [[ -e ${CONDOR_CONFIG_LOCAL} ]] || fatal_error "Missing local condor config file"
+    local key val
+    if [[ $# -eq 1 ]]; then # double quotes around args, or no spaces
+	key="${1%=*}"
+	val="${1##*=}"
+    elif [[ $# -eq 2 ]]; then # separated by one space
+	key="${1%=*}"
+	val="${2##*=}"
+    elif [[ $# -eq 3 ]]; then # 2 spaces, assume = in the middle
+	key="$1"
+	val="$3"
     else
-	echo $with_this >> $on_this_file
+	fatal_error "Cannot decode a key-value pair in $# arguments"
+    fi
+    [[ -z ${key} ]] && fatal_error "Cannot decode a key in $*"
+    [[ -z ${val} ]] && fatal_error "Cannot decode a value in $*"
+    # replace or append
+    if grep -q -e "^[ \t]*${key}*=" ${CONDOR_CONFIG_LOCAL}; then
+	sed -i -e "s/^\([ \t]*${key}[ \t]*\)=.*/\1=${val}/" ${CONDOR_CONFIG_LOCAL}
+    else
+	echo >> ${CONDOR_CONFIG_LOCAL} "# Added by cloud scheduler"
+	echo >> ${CONDOR_CONFIG_LOCAL} "${key} = ${val}"
     fi
 }
 
-set_central_manager() {
-    condor_host=$1
-
-    if [ "xxx" = "xxx${condor_host}" ]; then
-	
-	echo "CENTRAL_MANAGER is undefined. Check /etc/condor/central_manager" >&1
-	exit 1
-    fi
-    
-    local_file=`get_condor_config_val LOCAL_CONFIG_FILE`
-    replace_or_append "CONDOR_HOST" "CONDOR_HOST=$condor_host" $local_file
-}
-
-update_condor_local_config() {
-    if [ -f $CONDOR_CONFIG_LOCAL_MODIFS ]; then
-	local_file=`get_condor_config_val LOCAL_CONFIG_FILE`
-	echo "Applying modifications to ${local_file} ..."
-	while read LINE
-	do
-	    # Split values like 'variable = value'
-	    variable=`echo ${LINE} | perl -pe 's/(\w*?) \s*? = \s* (.*)/\1/x'`
-	    value=`echo ${LINE} | perl -pe 's/(\w*?) \s*? = \s* (.*)/\2/x'`
-	    replace_or_append "${variable}" "${variable}=${value}" $local_file
-	done < $CONDOR_CONFIG_LOCAL_MODIFS
-    fi
+# setup the condor_host
+setup_central_manager() {
+    local condor_host="$(cat ${CENTRAL_MANAGER} 2> /dev/null)"
+    [[ -z ${condor_host} ]] && \
+	fatal_error "CENTRAL_MANAGER is undefined, check ${CENTRAL_MANAGER}"
+    update_condor_config "CONDOR_HOST=${condor_host}"
 }
 
 # set up condor ccb if only private networking is available
 setup_ccb() {
-	/sbin/ifconfig | grep "inet addr" | egrep -v "addr:127.|addr:192.|addr:172.|addr:10." > /dev/null
-	NON_LOCAL=$?
-
-	if [ $NON_LOCAL -eq 1 ]; then
-	    # All addresses are local
-	    LOCAL_ADDRESS=`/sbin/ifconfig eth0 | grep "inet addr" | awk '{print $2}' | sed s/addr://`
-	    echo $LOCAL_ADDRESS $HOSTNAME "# Added for Condor CCB" >> /etc/hosts
-	fi
-}
-
-# usage: setup_vmtype metadata
-setup_vmtype() {
-    IMAGE_META_FILE=$1
-    
-    if [ -f $IMAGE_META_FILE ]; then
-	
-	# Parse VMType out of repoman metadata file
-	VMTYPE=`cat $IMAGE_META_FILE | awk -F: '/^name:/ { print $2 }' | sed  's/[ \t]* //'`
-
-	if [ "xxx" != "xxx${VMTYPE}" ]; then
-	    
-	    local_file=`get_condor_config_val LOCAL_CONFIG_FILE`
-	    replace_or_append "VMType" "VMType= \"$VMTYPE\"" $local_file
-	fi
+    if ${IFCONFIG} | grep "inet addr" | egrep -v "addr:127.|addr:192.|addr:172.|addr:10." > /dev/null; then
+	# ip  are local
+	echo  >> /etc/hosts \
+	    "$(${IFCONFIG} eth0 | grep -oP '(?<=inet addr:)[0-9.]*') ${HOSTNAME} # Added for Condor CCB"
     fi
 }
 
-setup_on_ec2() {
-    
-    local_file=`get_condor_config_val LOCAL_CONFIG_FILE`
-    
-    # Eucalyptus can give us just a private IP
-    public_ip=`curl -m 10 -s http://$EC2_METADATA/latest/meta-data/public-ipv4`
-    test $public_ip != "0.0.0.0" > /dev/null 2>&1
-    HAS_PUBLIC_IP=$?
-    
-    curl -m 10 -s http://$EC2_METADATA/ >/dev/null 2>&1
-    IS_EC2=$?
-    if [ $IS_EC2 -eq 0 ] ; then	
-	if [ $HAS_PUBLIC_IP -eq 0 ] ; then	    
-	    # Set hostname to external
-	    EXTHOSTNAME=`curl -s http://$EC2_METADATA/latest/meta-data/public-hostname`
-	    VALID_HOST=$?
-	    if [ $VALID_HOST -eq 0 ] ; then
-		hostname $EXTHOSTNAME
-		
-		private_network_name=amazon-ec2-`curl -s http://$EC2_METADATA/latest/meta-data/placement/availability-zone`
-		replace_or_append "PRIVATE_NETWORK_NAME" "PRIVATE_NETWORK_NAME=$private_network_name" $local_file
-		
-		tcp_forwarding_host=`curl -s http://$EC2_METADATA/latest/meta-data/public-ipv4`
-		replace_or_append "TCP_FORWARDING_HOST" "TCP_FORWARDING_HOST=$tcp_forwarding_host" $local_file
-		
-		private_network_interface=`curl -s http://$EC2_METADATA/latest/meta-data/local-ipv4`
-		replace_or_append "PRIVATE_NETWORK_INTERFACE" "PRIVATE_NETWORK_INTERFACE=$private_network_interface" $local_file
+# set the VMType for condor
+setup_vmtype() {
+    if [[ -n ${IMAGE_META_FILE} ]] && [[ -f ${IMAGE_META_FILE} ]]; then	
+	# Parse VMType out of repoman metadata file
+	# rely on python > 2.6 to get json file
+	local vmtype=$(${PYTHON} -c "import json; print(json.load(open('${IMAGE_META_FILE}'))['vmtype'])" 2> /dev/null)
+	[[ -z ${vmtype} ]] || update_condor_condig "VMType = \"${vmtype}\""
+    fi
+}
+
+# setup EC2 if used
+setup_ec2() {
+    [[ -z ${EC2_METADATA} ]] && return
+    local ec2url="http://${EC2_METADATA}/latest/meta-data"
+    local exthostname
+    # is it an ec2?
+    if curl -m 10 -s "http://${EC2_METADATA}/" > /dev/null 2>&1 ; then	
+	# does it have public ip?
+	if [[ $(curl -m 10 -s "${ec2url}/public-ipv4}") != 0.0.0.0 ]]; then
+	    # set hostname to external
+	    exthostname=$(curl -s "${ec2url}/public-hostname")
+	    if [[ $? -eq 0 ]]; then
+		hostname ${exthostname}		
+		update_condor_config "PRIVATE_NETWORK_NAME=amazon-ec2-$(curl -s ${ec2url}/placement/availability-zone)"
+		update_condor_config "TCP_FORWARDING_HOST=$(curl -s ${ec2url}/public-ipv4)"
+		update_condor_config "PRIVATE_NETWORK_INTERFACE=$(curl -s ${ec2url}/local-ipv4)"
 	    fi
 	else
-	    # Set hostname to instance id when we're using private net
-	    EXTHOSTNAME=`curl -s http://$EC2_METADATA/latest/meta-data/instance-id`
-	    VALID_ID=$?
-	    if [ $VALID_ID -eq 0 ] ; then
-		hostname $EXTHOSTNAME		
-		private_network_interface=`curl -s http://$EC2_METADATA/latest/meta-data/local-ipv4`
-		replace_or_append "PRIVATE_NETWORK_INTERFACE" "PRIVATE_NETWORK_INTERFACE=$private_network_interface" $local_file
+	    # set hostname to instance id when we're using private net
+	    exthostname=$(curl -s "${ec2url}/instance-id")
+	    if $? ; then
+		hostname ${exthostname}
+		update_condor_config "PRIVATE_NETWORK_INTERFACE=$(curl -s ${ec2url}/local-ipv4)"
 	    fi
 	fi
     fi
@@ -146,26 +115,37 @@ setup_on_ec2() {
 
 # Make sure the permissions on the grid hostkey
 # are restrictive enough, else GSI will fail.
-set_hostkey_permissions () {
-    HOST_KEY=`get_condor_config_val GSI_DAEMON_KEY`
-    if [ -f $HOST_KEY ]; then
-	chmod 400 $HOST_KEY
+setup_hostkey_permissions () {
+    local hostkey=$(condor_config_val GSI_DAEMON_KEY 2> /dev/null)
+    [[ -z ${hostkey} ]] && return
+    if [[ -f ${hostkey} ]]; then
+	chmod 400 ${hostkey}
     else
-	echo "Grid certificate host key not found. $HOST_KEY"
+	echo "Grid certificate host key not found: ${hostkey}" 2>&1
+    fi
+}
+
+apply_condor_modifs() {
+    if [[ -f ${CONDOR_CONFIG_LOCAL_MODIFS} ]]; then
+	local line
+	grep -v '^[ \t]*#' ${CONDOR_CONFIG_LOCAL_MODIFS} | while read -r line; do
+	    [[ -z ${line} ]] && continue
+	    update_condor_config "${line}"
+	done
     fi
 }
 
 cleanup_ccb () {
-    sed -i '/# Added for Condor CCB/d' /etc/hosts
+    sed -i -e '/# Added for Condor CCB/d' /etc/hosts
 }
 
 start() {
-    set_hostkey_permissions
-    setup_on_ec2
+    setup_hostkey_permissions
+    setup_ec2
     setup_ccb
-    set_central_manager $CENTRAL_MANAGER
-    setup_vmtype $IMAGE_METADATA
-    update_condor_local_config
+    setup_central_manager
+    setup_vmtype
+    apply_condor_modifs
     RETVAL=$?
 }
 
